### ISSUE TITLE
training time and infer image's size

### ISSUE THREAD

**Issue by nzhang258** [SHI-Labs/FcF-Inpainting#1]
Thanks for your amazing work. And I have some questions for your help:
 1) how long time have you trained with celeba-hq? 
2) In paper I see you trained 25M images, and the number of Celebahq is 30000, did this mean that you train the model with 800+ epochs? 
3) Can I change my inference image's size with model trained with 256*256? Do you have any suggestions if my test images have different size?
Look forward to your favourable reply~

**Comment by praeclarumjj3** [comment]
Hi @nzhang258, thanks for your interest in our work. Please find the answers to your questions below:

1. It takes us about 6.5 days to train a `256x256` celeba-hq model with 8 RTX A6000 GPUs.
2. You are partially correct. We follow [LaMa's](https://github.com/saic-mdal/lama#celeba) split strategy; hence, we have 26000 images in the training set. So, the training duration in terms of epochs is about 960.
3. We build up our work on [StyleGAN2](https://github.com/NVlabs/stylegan2-ada-pytorch) architecture, which only supports fixed size inference. If you have a different resolution image, you could either resize it to `256x256` or perform a random crop to `256x256`.

**Comment by nzhang258** [comment]
> Hi @nzhang258, thanks for your interest in our work. Please find the answers to your questions below:
> 
> 1. It takes us about 6.5 days to train a `256x256` celeba-hq model with 8 RTX A6000 GPUs.
> 2. You are partially correct. We follow [LaMa's](https://github.com/saic-mdal/lama#celeba) split strategy; hence, we have 26000 images in the training set. So, the training duration in terms of epochs is about 960.
> 3. We build up our work on [StyleGAN2](https://github.com/NVlabs/stylegan2-ada-pytorch) architecture, which only supports fixed size inference. If you have a different resolution image, you could either resize it to `256x256` or perform a random crop to `256x256`.

OK, thanks a lot for your reply~
