### ISSUE TITLE
ModuleNotFoundError: No module named 'training.augment'

### ISSUE THREAD

**Issue by Soulempty** [SHI-Labs/FcF-Inpainting#10]
Thanks for your great work,I encountered this problem while training using the '--augpipe=geom' parameter,i need some help about scaling the training images,thanks for your reply.

 python train.py   --outdir=training-runs-inp         
                             --img_data=datasets/demo/train        
                             --gpus 4         
                             --kimg 2000         
                             --gamma 10            
                             --metrics True        
                              --eval_img_data datasets/demo/evaluation/random_val 
                              --batch 8 
                              --resolution 512  
                              --augpipe geom

**Comment by praeclarumjj3** [comment]
Hi @Soulempty, thanks for your interest in our work. We don't use any augmentations during training, so I removed the support for doing that. If you want to train with augmentations, you might want to add an `augment.py` script inside the [`training`](https://github.com/SHI-Labs/FcF-Inpainting/tree/main/training) directory. You may refer to [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/augment.py) for creating the script.

**Comment by Soulempty** [comment]
Your answer is very helpful to me，Thanks for your reply.
