### ISSUE TITLE
stuck at compiling the basic act plugin

### ISSUE THREAD

**Issue by ImmortalSdm** [SHI-Labs/FcF-Inpainting#11]
![image](https://user-images.githubusercontent.com/40324192/206981875-2f61aa4d-ed20-4f55-b937-5ec915775ea0.png)

When i try to train fcf with my custom datasets, I'm facing the problem. Any ideas?

**Comment by praeclarumjj3** [comment]
Hi @ImmortalSdm, did you try following the instructions in the link under [`Note` mentioned in the Readme](https://github.com/SHI-Labs/FcF-Inpainting#training-on-256x256)?

Specifically, running the following command:
```python
rm -rf ~/.cache/torch_extensions
```

**Comment by ImmortalSdm** [comment]
> 

Thanks for your advise, it works!
