### ISSUE TITLE
can i use 1024 resolution when infer? and i want to know if i should train a model with 1024X1024 input?

### ISSUE THREAD

**Issue by dreamer121121** [SHI-Labs/FcF-Inpainting#14]
can i use 1024 resolution when infer? and i want to know if i should train a model with 1024X1024 input?

**Comment by praeclarumjj3** [comment]
Hi @dreamer121121, thanks for your interest in our work. 

> can i use 1024 resolution when infer?

You can (technically). However, you would have to interpolate the input size to 512x512 as our model does not support arbitrary inference sizes (built upon StyleGAN2).

>  i want to know if i should train a model with 1024X1024 input?

You should if you have the compute for training. Note that you might have to tune the hyper-parameters to ensure stability during training and achieve the best performance for 1024x1024 resolution.
