### ISSUE TITLE
Trained with 512x512 Input but not Converged

### ISSUE THREAD

**Issue by Bai426** [SHI-Labs/FcF-Inpainting#17]
Hi, authors. I used this repository to train with an input image size of 256x256, it worked very well and can converge when I looked at the FID score. However, after I changed the resolution from 256 to 512 in the corresponding files and keep other hyperparameters remained, I have to reduce the batch size for training (from 64 to 8), but the FID score is up during the training. Can you tell me how to handle this? Thank you very much!

Best,
Mike

**Comment by praeclarumjj3** [comment]
Hi @Bai426, the training is sensitive to the batch size. As explained in our paper, we use a batch size of 32 while training on 512x512. Could you increase the batch size from 8 to 32?

**Comment by Bai426** [comment]
Okay, I have issue of the GPU memory when I used batch size of 64 or 16. But let me try 32.

**Comment by praeclarumjj3** [comment]
> Okay, I have issue of the GPU memory when I used batch size of 64 or 16. But let me try 32.

You may have memory issues with batch size 32, then. Our `lr` is tuned for batch size 32. You might have to tune the hyperparameters for batch size 8. The training would be unstable otherwise

**Comment by Bai426** [comment]
Thank you very much!

**Comment by rose-jinyang** [comment]
Hi @Bai426 
I am going to train a model with 512x512 resolution on my own dataset.
When run the train script with resolution 512, I met the following issue.
![image](https://user-images.githubusercontent.com/47862419/230270645-aecbcf28-9840-42c2-ba68-a532030b52b5.png)

Could you guide me how to fix this issue?

**Comment by Bai426** [comment]
This problem is not caused by 512x512 dataset. I cannot remember very clear but the codes like module.py or other may have a minor mistake which is easily corrected. You can find it and make your codes work.

**Comment by rose-jinyang** [comment]
Thanks for your guide.

**Comment by rose-jinyang** [comment]
Hi @Bai426 
One more question.
Did you try to apply this inpainting method for high-resolution (ex: 2500x1700) images?
If so, how about the result in quality?

**Comment by Bai426** [comment]
No, I trained both 256 and 512 models. For high resolution one, you may need to try.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
