### ISSUE TITLE
FCF may generate unreasonable structure in real-world img

### ISSUE THREAD

**Issue by dreamer121121** [SHI-Labs/FcF-Inpainting#20]
hello,,I found that fcf sometimes may generate unreasonable structure in real-world img, and i found that it seems to copy some structures around mask region, could you please give some advices?

**Comment by praeclarumjj3** [comment]
Hi @dreamer121121, thanks for your interest. Could you share your findings here for a better demonstration?

**Comment by dreamer121121** [comment]
This is a badecase for you.
[error.tar.gz](https://github.com/SHI-Labs/FcF-Inpainting/files/10778948/error.tar.gz)

**Comment by praeclarumjj3** [comment]
Hi @dreamer121121, sorry for the delay in getting back to you. It is strange that you see such artifacts. Did you try changing the seed during inference? The artifacts seem to correspond to the ability of FFC to capture nearby patterns that in this case is happening with the human in middle. I would recommend changing the seed to check the variance in performance. You could also try modifying the `truncation_psi` value.

<div class="row">
    <img src="https://user-images.githubusercontent.com/54928629/220874060-4c25a82e-225a-471d-9ccb-10295c731009.JPG" width=300>
    <img src="https://user-images.githubusercontent.com/54928629/220874076-7bb41c9f-558a-4c00-aed5-c257cc99b052.JPG" width=300>
</div>

**Comment by dreamer121121** [comment]
> Hi @dreamer121121, sorry for the delay in getting back to you. It is strange that you see such artifacts. Did you try changing the seed during inference?
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/54928629/220874060-4c25a82e-225a-471d-9ccb-10295c731009.JPG"> <img alt="" width="300" src="https://user-images.githubusercontent.com/54928629/220874076-7bb41c9f-558a-4c00-aed5-c257cc99b052.JPG">

i think i'm not ,how to change the seed during inference?

**Comment by praeclarumjj3** [comment]
You can change the seed here
https://github.com/SHI-Labs/FcF-Inpainting/blob/653df3d72d8e7781e0458f564dba5f0f9ec6add0/demo.py#L102

**Comment by dreamer121121** [comment]
> 



> Hi @dreamer121121, sorry for the delay in getting back to you. It is strange that you see such artifacts. Did you try changing the seed during inference? The artifacts seem to correspond to the ability of FFC to capture nearby patterns that in this case is happening with the human in middle. I would recommend changing the seed to check the variance in performance. You could also try modifying the `truncation_psi` value.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/54928629/220874060-4c25a82e-225a-471d-9ccb-10295c731009.JPG"> <img alt="" width="300" src="https://user-images.githubusercontent.com/54928629/220874076-7bb41c9f-558a-4c00-aed5-c257cc99b052.JPG">

I tried to change the seed and truncation_psi but it didn't work,,, and i also test in validation dataset ,i found this phenomenon is very widespread such as :
![截屏2023-02-24 下午12 03 49](https://user-images.githubusercontent.com/35915584/221089156-d0205321-cb97-4928-8a8d-d3dd62e74a58.png)

**Comment by yzhouas** [comment]
Hi @dreamer121121 ,

Thanks for the feedback. We cannot expect the GAN-based model to work well on complicated object completion tasks (like completing the building / bus / geometry structures). Recently, diffusion-based generative model is demonstrating powerful ability of doing that. 

Our FCF-GAN based model may be better for texture completion, repeating pattern inpainting or other inpainting tasks which require heavy copy and pasting, and it is much faster than a diffusion-based model. 

For a better performance for people removel in front of a building, I strongly suggest to try cropping before running the FcFGAN. Reducing the sampling area will largely improve the inpainting results and make the model focus more on the detail generation. 

Thanks again for your testing, and we welcome any other testing images and feedbacks.
