### ISSUE TITLE
TypeError: run_G() missing 1 required positional argument: 'c'

### ISSUE THREAD

**Issue by Runing-Lab** [SHI-Labs/FcF-Inpainting#22]
Hello, I encountered this error when running train.py. 

`Traceback (most recent call last):
  File "train.py", line 523, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 516, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 391, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/FcF-Inpainting-main/training/training_loop.py", line 327, in training_loop
    loss.accumulate_gradients(phase=phase.name, erased_img=erased_img, real_img=real_img, mask=mask, real_c=real_c, gen_c=gen_c, sync=sync, gain=gain)
  File "/FcF-Inpainting-main/training/losses/loss.py", line 65, in accumulate_gradients
    gen_img, _ = self.run_G(g_inputs, gen_c, sync=sync) # May get synced by Gpl.
TypeError: run_G() missing 1 required positional argument: 'c'
`

The second is that I can't download the place2 dataset through wget.

`(myconda) root@PVGa1O:/FcF-Inpainting-main# wget http://data.csail.mit.edu/places/places365/train_large_places365challenge.tar
--2023-02-28 08:34:03--  http://data.csail.mit.edu/places/places365/train_large_places365challenge.tar
Resolving data.csail.mit.edu (data.csail.mit.edu)... 128.52.129.40
Connecting to data.csail.mit.edu (data.csail.mit.edu)|128.52.129.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-28 08:34:04 ERROR 404: Not Found.

(myconda) root@PVGa1O:/FcF-Inpainting-main#  wget http://data.csail.mit.edu/places/places365/val_large.tar
--2023-02-28 08:34:18--  http://data.csail.mit.edu/places/places365/val_large.tar
Resolving data.csail.mit.edu (data.csail.mit.edu)... 128.52.129.40
Connecting to data.csail.mit.edu (data.csail.mit.edu)|128.52.129.40|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-28 08:34:19 ERROR 404: Not Found.

(myconda) root@PVGa1O:/FcF-Inpainting-main# 
`

**Comment by praeclarumjj3** [comment]
Hi @lrn1314, thanks for your interest in our work.

I have fixed the issue responsible for the `TypeError: run_G() missing 1 required positional argument: 'c' ` error. Please try rerunning the code.

`Re Places2`: I believe the maintainers took down the dataset temporarily. You might need [to complete a form](http://places2.csail.mit.edu/download.html) to access the dataset now. 

<img width="1173" alt="Screenshot 2023-02-28 at 7 28 36 PM" src="https://user-images.githubusercontent.com/54928629/221875648-a60b7606-bcc1-4382-a344-a2b749342cea.png">

**Comment by Runing-Lab** [comment]
Thank you for your answer. The place2 dataset can be downloaded, but my computer is not so large. How can I run train.py with the celeA-HQ dataset? Because I just started to learn, I don't understand.

**Comment by praeclarumjj3** [comment]
Please follow the instructions to prepare the CelebA-HQ dataset given [here](https://github.com/SHI-Labs/FcF-Inpainting#celeba-hq-dataset). Then replace the `--img_data` and `--eval_img_data` arguments accordingly with [aths to the CelebA-HQ dataset.
