### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'mask_generator_kwargs'

### ISSUE THREAD

**Issue by RecruitXin** [SHI-Labs/FcF-Inpainting#25]
Hello, I encountered this error when running bash tools/prepare_places_segm_evaluation.sh

Detectron v2 is not installed
Traceback (most recent call last):
  File "tools/gen_random_segm_masks.py", line 123, in <module>
    main(aparser.parse_args())
  File "tools/gen_random_segm_masks.py", line 103, in main
    process_images(in_files, args.indir, args.outdir, config)
  File "tools/gen_random_segm_masks.py", line 28, in process_images
    mask_generator = SegmentationMask(**config.mask_generator_kwargs)
AttributeError: 'EasyDict' object has no attribute 'mask_generator_kwargs'

**Comment by praeclarumjj3** [comment]
Hi @RecruitXin, please install Detectron2: https://github.com/SHI-Labs/FcF-Inpainting/tree/55ac6a06ec25834edcd385a1f7be05b55cbc1f9c#segmentation-mask-strategy.

If it still doesn't work, could you try replacing `mask_generator = SegmentationMask(**config.mask_generator_kwargs)` with `mask_generator = SegmentationMask(**config.mask_gen_kwargs)` in `tools/gen_random_segm_masks.py`.

https://github.com/SHI-Labs/FcF-Inpainting/blob/55ac6a06ec25834edcd385a1f7be05b55cbc1f9c/tools/gen_random_segm_masks.py#L27

**Comment by praeclarumjj3** [comment]
Closed due to inactivity. Feel free to re-open if the issue persists.
