### ISSUE TITLE
RuntimeError: Output 0 of SliceBackward0 is a view and is being modified inplace. 

### ISSUE THREAD

**Issue by Nyoko74** [SHI-Labs/FcF-Inpainting#26]
Thanks for your excellent work, but I have encountered some problems.
I got an error when using multiple GPUs:
`Traceback (most recent call last):`
  `File "/anaconda3/envs/pytorch_1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args)`
 ` File "/nfs/PycharmProjects/FcF-Inpainting/train.py", line 393, in subprocess_fn training_loop.training_loop(rank=rank, **args)`
  `File "/nfs/PycharmProjects/FcF-Inpainting/training/training_loop.py", line 327, in training_loop `
`loss.accumulate_gradients(phase=phase.name, erased_img=erased_img, real_img=real_img, mask=mask, real_c=real_c, gen_c=gen_c, sync=sync, gain=gain)`
`  File "/nfs/PycharmProjects/FcF-Inpainting/training/losses/loss.py", line 65, in accumulate_gradients gen_img, _ =self.run_G(g_inputs, mask, gen_c, sync=sync) # May get synced by Gpl.`
`  File "/nfs/PycharmProjects/FcF-Inpainting/training/losses/loss.py", line 44, in run_G`
`    ws[:, cutoff:] = self.G_mapping(torch.randn_like(z), c, skip_w_avg_update=True)[:, cutoff:]`
`RuntimeError: Output 0 of SliceBackward0 is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.`
But when I only run on one GPU, everything is fine.
How should I solve it?

**Comment by Nyoko74** [comment]
> 感谢您的出色工作，但我遇到了一些问题。 使用多个 GPU 时出现错误： `Traceback (most recent call last):` `File "/anaconda3/envs/pytorch_1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args)` ` File "/nfs/PycharmProjects/FcF-Inpainting/train.py", line 393, in subprocess_fn training_loop.training_loop(rank=rank, **args)` `File "/nfs/PycharmProjects/FcF-Inpainting/training/training_loop.py", line 327, in training_loop ` `loss.accumulate_gradients(phase=phase.name, erased_img=erased_img, real_img=real_img, mask=mask, real_c=real_c, gen_c=gen_c, sync=sync, gain=gain)` ` File "/nfs/PycharmProjects/FcF-Inpainting/training/losses/loss.py", line 65, in accumulate_gradients gen_img, _ =self.run_G(g_inputs, mask, gen_c, sync=sync) # May get synced by Gpl.` ` File "/nfs/PycharmProjects/FcF-Inpainting/training/losses/loss.py", line 44, in run_G` ` ws[:, cutoff:] = self.G_mapping(torch.randn_like(z), c, skip_w_avg_update=True)[:, cutoff:]` `RuntimeError: Output 0 of SliceBackward0 is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.` 但是当我只在一个 GPU 上运行时，一切正常。 我该如何解决？

**Comment by praeclarumjj3** [comment]
Hi @Nyoko74, thanks for your interest in our work. I can successfully train a model on multiple RTX A6000 GPUs on my end with the specified [repo environment ](https://github.com/SHI-Labs/FcF-Inpainting#1-setup-instructions).

Could you provide more information about your environment and hardware?

**Comment by Nyoko74** [comment]
> Hi @Nyoko74, thanks for your interest in our work. I can successfully train a model on multiple RTX A6000 GPUs on my end with the specified [repo environment ](https://github.com/SHI-Labs/FcF-Inpainting#1-setup-instructions).
> 
> Could you provide more information about your environment and hardware?

I run on 2 RTX 3080 GPUs.  I install pytorch 1.10.1, and all packages in requirements.txt.

I make it work by fix the code
 `ws[:, cutoff:] = self.G_mapping(torch.randn_like(z), c, skip_w_avg_update=True)[:, cutoff:]`
 in /training/losses/loss.py, line 44(https://github.com/SHI-Labs/FcF-Inpainting/blob/main/training/losses/loss.py#L44)
to:
```
output = self.G_mapping(torch.randn_like(z), c, skip_w_avg_update=True)
ws_clone = ws.clone()
ws_clone[:, cutoff:] = output[:, cutoff:]
ws = ws_clone
```
Will this affect the results?

**Comment by praeclarumjj3** [comment]
You are facing most probably because of a different `Pytorch` than what we recommend (`1.7.1`).

> Will this affect the results?

It should not since you are just creating a clone for a tensor and nothing more.

**Comment by Nyoko74** [comment]
> You are facing most probably because of a different `Pytorch` than what we recommend (`1.7.1`).
> 
> > Will this affect the results?
> 
> It should not since you are just creating a clone for a tensor and nothing more.

Ok, thank you very much!
