### ISSUE TITLE
question about input c，  is it important？

### ISSUE THREAD

**Issue by dongshenhan** [SHI-Labs/FcF-Inpainting#28]

**Comment by dongshenhan** [comment]
i found that all c ,grid_c  is empty,which is the generate or discriminator input , is it important?    i confused about that,,,,,,,,,,,,,,,thank you

**Comment by praeclarumjj3** [comment]
Hi @dongshenhan, thanks for your interest in our work. The `c` tensor is the class label for conditioning the network on the class when it is present. We do not use any condition on class for FcF-Inpainting.
