### ISSUE TITLE
Process of high-resolution images

### ISSUE THREAD

**Issue by rose-jinyang** [SHI-Labs/FcF-Inpainting#29]
Hello
How are you?
Thanks for contributing to this project.
The Lama model was trained with 256x256 size of image but it is robust for higher resolution images (ex: 2900x1800) by the with refinement process (https://arxiv.org/pdf/2206.13644.pdf).
I'm curious if this FcF method can be applied for high-resolution input as 2900x1800.
If the image resolution is very high as 2900x1800 and the hole mask size is also bigger than 256x256 or 512x512, how can this method be applied to such images?
Is it possible to integrate such a refinement process like in Lama for high resolution image?

**Comment by praeclarumjj3** [comment]
Hi @rose-jinyang, FCF-Inpainting is based on the StyleGAN2 architecture, so it only allows fixed resolution inference at present.

**Comment by rose-jinyang** [comment]
So is it impossible to get high-resolution image by your method?

**Comment by praeclarumjj3** [comment]
You can try training a new model at a higher resolution or perform inference in patches to obtain high-resolution results.
