### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'ws'

### ISSUE THREAD

**Issue by ousinkou** [SHI-Labs/FcF-Inpainting#3]
When I run train.py, this error occurs.  StyleGAN2Loss in loss.py, line 45.
```
 with misc.ddp_sync(self.G_synthesis, sync):
            img = self.G_synthesis(x_global, feats, ws)
```
But G_synthesis need four parameters to run forward. There's no parameter mask here.
Did I get something wrong?

**Comment by praeclarumjj3** [comment]
Hi @ousinkou, thanks for your interest in our work. 

Thanks for pointing this out! I believe I mistakenly deleted an argument from the forward call while cleaning the codebase. I have fixed the issue in the most recent commit. Could you try again?
https://github.com/SHI-Labs/FcF-Inpainting/blob/850964f09a50a5c30fac64461f1be8f7c1a77a89/training/losses/loss.py#L46

Let me know if you face any more issues.

**Comment by ousinkou** [comment]
Hi @praeclarumjj3 , very thank you for the quick reply.
But SynthesisBlock can't accept the mask=None.
https://github.com/SHI-Labs/FcF-Inpainting/blob/850964f09a50a5c30fac64461f1be8f7c1a77a89/training/models.py#L521
https://github.com/SHI-Labs/FcF-Inpainting/blob/850964f09a50a5c30fac64461f1be8f7c1a77a89/training/models.py#L533
I modify the if condition to
`if len(self.ffc_skip) > 0 and mask is not None`
The code can run successfully but I don't know if it's correct.

**Comment by praeclarumjj3** [comment]
Yes, @ousinkou, it's correct. We are not using the mask anywhere inside the generator. The argument is there because of an older experiment. We can also pass the real mask not to change the `if` condition. Let me make the required changes. Thanks for pointing it out again!
