### ISSUE TITLE
Training 512x512 model

### ISSUE THREAD

**Issue by rose-jinyang** [SHI-Labs/FcF-Inpainting#30]
Hello
How are you?
Thanks for contributing to this project.
I am going to train a 512x512 model on my own data.
But I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/230247912-2a1adf09-fcf2-4266-90ab-ca3a5e5266d0.png)

I set the resolution parameter to 512 in the script "train.py"

**Comment by praeclarumjj3** [comment]
Hi @rose-jinyang, thanks for your interest in our work. Where exactly did you set `resolution=512`? It would be helpful if you could share more information about the change.

**Comment by rose-jinyang** [comment]
Hi @praeclarumjj3 
Thanks for your reply.
![image](https://user-images.githubusercontent.com/47862419/230898046-ae029a3e-5d70-4109-b48d-2bee2fe4b91a.png)

**Comment by praeclarumjj3** [comment]
Looks like you missed a `\` after specifying the `--img_data`. So, the script doesn't read the `--resolution` argument. Please try the following command:

```bash
python train.py \
  --outdir=training-runs-inp \
  --img_data=/mnt/sdb1/Jin/Data/cart_and_goods/train \
  --gpus 2 \
  --kimg 25000 \
  --gamma 10 \
  --aug 'noaug' \
  --metrics True \
  --eval_img_data /mnt/sdb1/Jin/Data/cart_and_goods/val/random_medium_256 \
  --batch 64 \
  --resolution 512
```

**Comment by rose-jinyang** [comment]
Oh, Thank you very much.
