### ISSUE TITLE
Lama Cleaner add FcF model support

### ISSUE THREAD

**Issue by Sanster** [SHI-Labs/FcF-Inpainting#4]
Thank you for open-sourcing your code and pre-training model. I maintain an inpainting tool [Lama Cleaner](https://github.com/Sanster/lama-cleaner) that allows anyone to easily use the SOTA inpainting model. If anyone is interested, you can check out the project's [repo](https://github.com/Sanster/lama-cleaner).

||LaMa|FcF|
|-----|-----|-----|
|![texture](https://user-images.githubusercontent.com/3998421/188305027-a4260545-c24e-4df7-9739-ac5dc3cae879.jpeg)|![texture_lama](https://user-images.githubusercontent.com/3998421/188305024-2064ed3e-5af4-4843-ac10-7f9da71e15f8.jpeg)|![texture_fcf](https://user-images.githubusercontent.com/3998421/188305006-a08d2896-a65f-43d5-b9a5-ef62c3129f0c.jpeg)|

**Comment by praeclarumjj3** [comment]
Hi @Sanster, thanks for integrating FcF-Inpainting into Lama Cleaner! The tool looks fantastic. We have also added a reference to your tool in the [News section in the Readme](https://github.com/SHI-Labs/FcF-Inpainting#news).
