### ISSUE TITLE
pretrain model can't download

### ISSUE THREAD

**Issue by CodeMadUser** [SHI-Labs/FcF-Inpainting#5]
hello,it's amazing.Thank you for your sharing.But when I download your pretrain model,it opens a document.Could you please share your pretrain model with Google drive.Thank you. Besides that, my computer has only one GPU, how do I train the network? Can I just modify the parameters of the number of GPUs trained?

**Comment by praeclarumjj3** [comment]
Hi @CodeMadUser, thanks for your interest in our work. Could you try downloading the models with `wget`?

```bash
wget https://shi-labs.com/projects/fcf-inpainting/places_512.pkl
wget https://shi-labs.com/projects/fcf-inpainting/places.pkl
wget https://shi-labs.com/projects/fcf-inpainting/celeba-hq.pkl
```

You should be able to train on a single GPU. However, you might need to decrease the batch size (to prevent OOM). You might also need to tune other hyper-parameters for single-gpu training.

**Comment by CodeMadUser** [comment]
> Hi @CodeMadUser, thanks for your interest in our work. Could you try downloading the models with `wget`?
> 
> ```shell
> wget https://shi-labs.com/projects/fcf-inpainting/places_512.pkl
> wget https://shi-labs.com/projects/fcf-inpainting/places.pkl
> wget https://shi-labs.com/projects/fcf-inpainting/celeba-hq.pkl
> ```
> 
> You should be able to train on a single GPU. However, you might need to decrease the batch size (to prevent OOM). You might also need to tune other hyper-parameters for single-gpu training.

thanks for your replying. I'll try on your suggestions.

**Comment by praeclarumjj3** [comment]
I am closing this issue. Feel free to re-open if you still face any challenges.

**Comment by CodeMadUser** [comment]
> I am closing this issue. Feel free to re-open if you still face any challenges.

thank you very much!I will continue to study the model and will communicate with you again if there are new developments。

**Comment by Ellohiye** [comment]
> hello,it's amazing.Thank you for your sharing.But when I download your pretrain model,it opens a document.Could you please share your pretrain model with Google drive.Thank you. Besides that, my computer has only one GPU, how do I train the network? Can I just modify the parameters of the number of GPUs trained?

hi! I see that you are also reproducing this paper. Can we add contact information to communicate? qq:3559640395
