### ISSUE TITLE
HF spaces not working on custom images throwing the following error

### ISSUE THREAD

**Issue by ofirkris** [SHI-Labs/FcF-Inpainting#9]
Thanks for making your great work available as a demo too, when trying to run it on a custom image I get the following error:
RuntimeError: "unfolded2d_copy" not implemented for 'Half'

**Comment by praeclarumjj3** [comment]
Hi @ofirkris, thanks for your interest. We are aware of the issue with the demo on HF space. The demo must be hosted on a GPU server. However, currently, the space only has a CPU backend. If you have a GPU machine, you can easily setup your demo as we have open-sourced the code for the demo [here](https://github.com/SHI-Labs/FcF-Inpainting/tree/main/streamlit_demo.)
